language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      dist: trusty
      compiler: clang
    - os: windows

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .